package com.faceunity.core.enumeration

import com.faceunity.wrapper.faceunity

/**
 *
 * DESC：AI驱动类型
 * Created on 2021/1/26
 *
 */
enum class FUAITypeEnum(val type: Int) {
    FUAITYPE_BACKGROUNDSEGMENTATION(faceunity.FUAITYPE_BACKGROUNDSEGMENTATION),
    FUAITYPE_HAIRSEGMENTATION(faceunity.FUAITYPE_HAIRSEGMENTATION),
    FUAITYPE_HANDGESTURE(faceunity.FUAITYPE_HANDGESTURE),
    FUAITYPE_TONGUETRACKING(faceunity.FUAITYPE_TONGUETRACKING),
    FUAITYPE_FACELANDMARKS75(faceunity.FUAITYPE_FACELANDMARKS75),
    FUAITYPE_FACELANDMARKS209(faceunity.FUAITYPE_FACELANDMARKS209),
    FUAITYPE_FACELANDMARKS239(faceunity.FUAITYPE_FACELANDMARKS239),
    FUAITYPE_HUMANPOSE2D(faceunity.FUAITYPE_HUMANPOSE2D),
    FUAITYPE_BACKGROUNDSEGMENTATION_GREEN(faceunity.FUAITYPE_BACKGROUNDSEGMENTATION_GREEN),
    FUAITYPE_FACEPROCESSOR(faceunity.FUAITYPE_FACEPROCESSOR),
    FUAITYPE_FACEPROCESSOR_FACECAPTURE(faceunity.FUAITYPE_FACEPROCESSOR_FACECAPTURE),
    FUAITYPE_FACEPROCESSOR_FACECAPTURE_TONGUETRACKING(faceunity.FUAITYPE_FACEPROCESSOR_FACECAPTURE_TONGUETRACKING),
    FUAITYPE_FACEPROCESSOR_HAIRSEGMENTATION(faceunity.FUAITYPE_FACEPROCESSOR_HAIRSEGMENTATION),
    FUAITYPE_FACEPROCESSOR_HEADSEGMENTATION(faceunity.FUAITYPE_FACEPROCESSOR_HEADSEGMENTATION),
    FUAITYPE_FACEPROCESSOR_EXPRESSION_RECOGNIZER(faceunity.FUAITYPE_FACEPROCESSOR_EXPRESSION_RECOGNIZER),
    FUAITYPE_FACEPROCESSOR_EMOTION_RECOGNIZER(faceunity.FUAITYPE_FACEPROCESSOR_EMOTION_RECOGNIZER),
    FUAITYPE_HUMAN_PROCESSOR(faceunity.FUAITYPE_HUMAN_PROCESSOR),
    FUAITYPE_HUMAN_PROCESSOR_DETECT(faceunity.FUAITYPE_HUMAN_PROCESSOR_DETECT),
    FUAITYPE_HUMAN_PROCESSOR_2D_SELFIE(faceunity.FUAITYPE_HUMAN_PROCESSOR_2D_SELFIE),
    FUAITYPE_HUMAN_PROCESSOR_2D_DANCE(faceunity.FUAITYPE_HUMAN_PROCESSOR_2D_DANCE),
    FUAITYPE_HUMAN_PROCESSOR_2D_SLIM(faceunity.FUAITYPE_HUMAN_PROCESSOR_2D_SLIM),
    FUAITYPE_HUMAN_PROCESSOR_3D_SELFIE(faceunity.FUAITYPE_HUMAN_PROCESSOR_3D_SELFIE),
    FUAITYPE_HUMAN_PROCESSOR_3D_DANCE(faceunity.FUAITYPE_HUMAN_PROCESSOR_3D_DANCE),
    FUAITYPE_HUMAN_PROCESSOR_SEGMENTATION(faceunity.FUAITYPE_HUMAN_PROCESSOR_SEGMENTATION)
}