package com.faceunity.core.model.facebeauty


/**
 *
 * DESC：美颜滤镜枚举
 * Created on 2020/12/21
 *
 */
object FaceBeautyFilterEnum {
    const val ORIGIN = "origin"
    const val FENNEN_1 = "fennen1"
    const val FENNEN_2 = "fennen2"
    const val FENNEN_3 = "fennen3"
    const val FENNEN_4 = "fennen4"
    const val FENNEN_5 = "fennen5"
    const val FENNEN_6 = "fennen6"
    const val FENNEN_7 = "fennen7"
    const val FENNEN_8 = "fennen8"
    const val XIAOQINGXIN_1 = "xiaoqingxin1"
    const val XIAOQINGXIN_2 = "xiaoqingxin2"
    const val XIAOQINGXIN_3 = "xiaoqingxin3"
    const val XIAOQINGXIN_4 = "xiaoqingxin4"
    const val XIAOQINGXIN_5 = "xiaoqingxin5"
    const val XIAOQINGXIN_6 = "xiaoqingxin6"
    const val BAILIANG_1 = "bailiang1"
    const val BAILIANG_2 = "bailiang2"
    const val BAILIANG_3 = "bailiang3"
    const val BAILIANG_4 = "bailiang4"
    const val BAILIANG_5 = "bailiang5"
    const val BAILIANG_6 = "bailiang6"
    const val BAILIANG_7 = "bailiang7"
    const val LENGSEDIAO_1 = "lengsediao1"
    const val LENGSEDIAO_2 = "lengsediao2"
    const val LENGSEDIAO_3 = "lengsediao3"
    const val LENGSEDIAO_4 = "lengsediao4"
    const val LENGSEDIAO_5 = "lengsediao5"
    const val LENGSEDIAO_6 = "lengsediao6"
    const val LENGSEDIAO_7 = "lengsediao7"
    const val LENGSEDIAO_8 = "lengsediao8"
    const val LENGSEDIAO_9 = "lengsediao9"
    const val LENGSEDIAO_10 = "lengsediao10"
    const val LENGSEDIAO_11 = "lengsediao11"
    const val NUANSEDIAO_1 = "nuansediao1"
    const val NUANSEDIAO_2 = "nuansediao2"
    const val NUANSEDIAO_3 = "nuansediao3"
    const val HEIBAI_1 = "heibai1"
    const val HEIBAI_2 = "heibai2"
    const val HEIBAI_3 = "heibai3"
    const val HEIBAI_4 = "heibai4"
    const val HEIBAI_5 = "heibai5"
    const val GEXING_1 = "gexing1"
    const val GEXING_2 = "gexing2"
    const val GEXING_3 = "gexing3"
    const val GEXING_4 = "gexing4"
    const val GEXING_5 = "gexing5"
    const val GEXING_6 = "gexing6"
    const val GEXING_7 = "gexing7"
    const val GEXING_8 = "gexing8"
    const val GEXING_9 = "gexing9"
    const val GEXING_10 = "gexing10"
    const val GEXING_11 = "gexing11"
    const val ZIRAN_1 = "ziran1"
    const val ZIRAN_2 = "ziran2"
    const val ZIRAN_3 = "ziran3"
    const val ZIRAN_4 = "ziran4"
    const val ZIRAN_5 = "ziran5"
    const val ZIRAN_6 = "ziran6"
    const val ZIRAN_7 = "ziran7"
    const val ZIRAN_8 = "ziran8"
    const val ZHIGANHUI_1 = "zhiganhui1"
    const val ZHIGANHUI_2 = "zhiganhui2"
    const val ZHIGANHUI_3 = "zhiganhui3"
    const val ZHIGANHUI_4 = "zhiganhui4"
    const val ZHIGANHUI_5 = "zhiganhui5"
    const val ZHIGANHUI_6 = "zhiganhui6"
    const val ZHIGANHUI_7 = "zhiganhui7"
    const val ZHIGANHUI_8 = "zhiganhui8"
    const val MITAO_1 = "mitao1"
    const val MITAO_2 = "mitao2"
    const val MITAO_3 = "mitao3"
    const val MITAO_4 = "mitao4"
    const val MITAO_5 = "mitao5"
    const val MITAO_6 = "mitao6"
    const val MITAO_7 = "mitao7"
    const val MITAO_8 = "mitao8"
}